<a href="https://colab.research.google.com/github/Biyong-Jeong/Colab_examples/blob/main/Colab_computerVision(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 뉴런 계층화 구현

import numpy as np

class FullyConnectedLayer(object):
  def __init__(self, num_inputs, layer_size, activation_fn):
    super().__init__()
    self.W = np.random.standard_normal((num_inputs, layer_size))
    self.b = np.random.standard_normal(layer_size)
    self.size = layer_size
    self.activation_fn = activation_fn

  def forward(self, x):
    z = np.dot(x, self.W) + self.b
    return self.activation_fn(z)


In [ ]:
# 뉴런 계층화 구현의 실제 실행
np.random.seed(42)

x1 = np.random.uniform(-1,1,2).reshape(1,2)
print(x1)
x2 = np.random.uniform(-1,1,2).reshape(1,2)
print(x2)

relu_fn = lambda y: np.maximum(y,0)
layer = FullyConnectedLayer(2,3,relu_fn)

#개별 처리
out1 = layer.forward(x1)
print(out1)
out2 = layer.forward(x2)
print(out2)

x12 = np.concatenate((x1, x2))
out12 = layer.forward(x12)
print(out12)

[[-0.25091976  0.90142861]]
[[0.46398788 0.19731697]]
[[0.28712364 0.         0.33478571]]
[[0.         0.         1.08175419]]
[[0.28712364 0.         0.33478571]
 [0.         0.         1.08175419]]


일반적으로 tensorflow 또는 Pytorch에 이미 dataset에 있는 mnist이지만 이 자료 자체를 사용하려고 하면 해당 사이트에 가서 git clone으로 불러와야 책에서 설명하는 내용대로 실습이 가능하다

In [ ]:
!git clone https://github.com/datapythonista/mnist.git

fatal: destination path 'mnist' already exists and is not an empty directory.


In [ ]:
#Mnist data loading 및 간단한 전처리
import numpy as np
import mnist
np.random.seed(42)

#훈련 및 테스트 데이터 로딩
X_train, y_train = mnist.train_images(), mnist.train_labels()
X_test, y_test = mnist.test_images(), mnist.test_labels()
num_classes = 10

#이미지를 컬럼 벡터로 변환
X_train, X_test = X_train.reshape(-1, 28*28), X_test.reshape(-1, 28*28)
#레이블을 원-핫 벡터로 변환
y_train = np.eye(num_classes)[y_train]

AttributeError: ignored