<a href="https://colab.research.google.com/github/Biyong-Jeong/Colab_examples/blob/main/ComputerVisioni(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

class Neuron(object):
  def __init__(self, num_inputs, activation_fn):
    super().__init__()
    self.W = np.random.rand(num_inputs)
    self.b = np.random.rand(1)
    self.activation_fn = activation_fn

  def forward(self, x):
    z = np.dot(x, self.W) + self.b
    return self.activation_fn(z)

In [ ]:
np.random.seed(42)

x = np.random.rand(3).reshape(1,3)
x

array([[0.37454012, 0.95071431, 0.73199394]])

In [ ]:
step_fn = lambda y: 0 if y<=0 else 1
perceptron = Neuron(num_inputs=x.size, activation_fn = step_fn)

In [ ]:
perceptron.W

array([0.59865848, 0.15601864, 0.15599452])

In [ ]:
perceptron.b

array([0.05808361])

In [ ]:
out = perceptron.forward(x)
out

1